name: "Check user authorization"
description: "Checks if the calling user has enough permission to perform action"

inputs:
  allowed_roles:
    description: "Space-separated list of roles that are allowed"
    required: true
    default: "admin"
  github_token:
    description: "GitHub token for API authentication"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check authorization level of dispatching user
      shell: bash
      run: |
        USER_ROLE=$(curl -s -H "Authorization: token ${{ inputs.github_token }}" \
          "https://api.github.com/repos/${{ github.repository }}/collaborators/${{ github.actor }}/permission" | jq -r .permission)

        echo "User ${{ github.actor }} has role: \"$USER_ROLE\""
        IFS=' ' read -ra ROLES <<< "${{ inputs.allowed_roles }}"
        for role in "${ROLES[@]}"; do
          if [[ "$USER_ROLE" == "$role" ]]; then
            echo "User is authorized"
            exit 0
          fi
        done

        echo "User is not authorized to perform this operation"
        exit 1
